# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e7d37031b6e17b71f59c65f362ba7b0da64a59cec3091832dc192fc86b21e3f3378a893d8d73645a18553ad8b6bf3f465bd8d5f23e11c7b80fce39eadb9e183

test:
  secret_key_base: 13b3b5988923da611e64bc6b53a53d163055145e43c1f9976b6d823aa158682b0583b20596247ef4d29fe91010699bf3cd6b4019f2ea854a2a1ab5822676ceee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
